### ISSUE TITLE
Caleb Suggestions

### ISSUE THREAD

**Issue by axhon** [Lambda-School-Labs/CS9-KnowledgeRocket#111]
## Home

- [x] Remove Sign up and Sign in on footer
-  - [x] Replace with Get Started

- [x] Remove `-` from `Sign-Out`

- [x] Sign In and Sign Up
-  - [x] Give Placeholders on Auth
-  - [x] Remove the Card Flip until after google auth wenth through.

- [x] On Rocket edit: `All fields required` warning not shown

- [x] Clip out green part of spreadsheet image on import csv preview

- [x] On Cohort, change Save Class Settings

- [x] Add Rocket to have a search field and filter the rockets

- [x] Add student should work with enter on submit
-  - [x] it adds a student
-  - [x] it clears the fields
-  - [x] it returns to the first field

- [x] On Settings page
-  - [x] Specify the User account settings what the email mean
-  -  -  [x] Like cc = copy on rocket ; Caleb read CC as credit card

**Comment by designerexpert** [comment]
CSV Image for Excel is fixed on my latest RP.

**Comment by BigBricks** [comment]
- [x] Give Placeholders on Auth

**Comment by axhon** [comment]
This issue is still being worked on.

**Comment by JustinSHong** [comment]
We decided to keep the card flip for 3rd party authentication because the card shows the user the status of their log in. The message shown will change depending on if the user is logging in, the user logs in, or the user fails to log in.
