### ISSUE TITLE
Settings form does not update user credentials

### ISSUE THREAD

**Issue by JustinSHong** [Lambda-School-Labs/CS9-KnowledgeRocket#119]
User credentials are not updated by the settings form when trying to submit a new password and rocket email. In this case a 404 error arises for the PUT request responsible for updating user.

The settings form also "hangs", user status stays at UPDATING_USER, when a user partially fills out the form and attempts to submit. In this case, form validation or a more robust PUT request that recognizes only a new password or a new email needs to be updated may resolve this case.

**Comment by designerexpert** [comment]
If its a fake email it does not do it, because it attempts to send an email to the user telling them of the change.
